name: dokku-presentation

pre_window: source .env

startup_window: 0

windows:
  - hello-app:
    - echo "Hello application" | figlet -w 300 | lolcat
    - ./scripts/start_hello_app.sh
  - todo-app:
    - echo "Todo application" | figlet -w 300 | lolcat
    - ./scripts/start_todo_app.sh
  - installation:
    - ./scripts/init_scaleway_server.sh
    - ./scripts/drive_install_dokku.sh
